name: Build & Save debian docker image for FBOSS
run-name: Build & Save debian docker image for FBOSS
on:
  pull_request:
  # Allow manually triggering the workflow
  workflow_dispatch:
  # Also schedule the workflow to run every 3 hours during day only
  # ShipIt job will sync hourly around HH:21, so schedule the run with 15 minute offset
  schedule:
    # Run weekly on Mondays
    - cron: '0 0 * * 1'
jobs:
  export-debian-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: sudo rm -rf ${{ github.workspace }}/*
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Build & Save debian docker image
        run: ./fboss/oss/docker/prefetch/build_image.sh ${{ github.workspace }}/fboss_debian_docker_image.tar.zst debian
      - name: Upload docker image
        uses: actions/upload-artifact@v6
        with:
          name: fboss_debian_docker_image.tar.zst
          path: ${{ github.workspace }}/fboss_debian_docker_image.tar.zst
          compression-level: 0
          # Explicitly set the retention at the object level
          retention-days: 14
